apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-medium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-medium
  template:
    metadata:
      labels:
        app: nginx-medium
    spec:
      containers:
        - name: nginx-medium-container
          image: mateonicoud/dymakube
          ports:
              - containerPort: 80