name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the Docker image
        run: docker build nginx-chapitre5-lesson1 --file nginx-chapitre5-lesson1/Dockerfile --tag mateonicoud/dymakube:latest
      - name: Push the Docker image
        run: docker push mateonicoud/dymakube:latest
